Repository uxplorerss/uxplorers-frontend, pull requests merged in 2024-12, with the labels that each got.

#53 fix/type-errors-and-semantic-markup
  src/pages/booking/index.tsx
  src/stores/useSearchQueryStore/index.ts
  src/stores/useSearchQueryStore/index.types.ts
Labels: bug

#50 Feat/5 reservation page
  .storybook/main.ts
  README.md
  index.html
  package-lock.json
  package.json
  public/404.html
  public/manifest.json
  src/assets/booking/btn_leftArrowMonth.svg
  src/assets/booking/btn_rightArrowMonth.svg
  src/assets/booking/btn_terminalMap.svg
  src/common/components/index.ts
  src/constants/terminal2.json
  src/constants/terminal_region.json
  src/pages/booking/arrivalLocation/index.styles.ts
  src/pages/booking/arrivalLocation/index.tsx
  src/pages/booking/departLocation/index.styles.ts
  src/pages/booking/departLocation/index.tsx
  src/pages/booking/index.styles.ts
  src/pages/booking/index.tsx
  src/routes/account/index.lazy.tsx
  src/routes/booking/arrivalLocation/index.tsx
  src/routes/booking/departLocation/index.tsx
  src/routes/booking/index.tsx
  src/routes/booking/tickets/index.tsx
  src/routes/booking/trips/index.tsx
  src/stores/useSearchQueryStore/index.ts
  src/stores/useSearchQueryStore/index.types.ts
  tsconfig.app.json
  yarn.lock
Labels: enhancement, Page

#63 feat/persist-purchased-ticket-list
  src/stores/useReservationStore/index.ts
Labels: enhancement

#57 feat: Booking Page
  src/assets/ArrowRightLongIcon.svg
  src/assets/CalendarIcon.svg
  src/assets/CheckCircleOutlinedIcon.svg
  src/assets/SeatIcon.svg
  src/assets/SmallPersonIcon.svg
  src/common/components/CompanyRow/index.styles.ts
  src/common/components/CompanyRow/index.tsx
  src/common/components/CompanyRow/index.types.ts
  src/common/components/Divider/index.styles.ts
  src/common/components/Divider/index.tsx
  src/common/components/Divider/index.types.ts
  src/common/components/FeeSumRow/index.tsx
  src/common/components/FeeSumRow/index.types.ts
  src/common/components/PrimaryCard/index.styles.ts
  src/common/components/PrimaryCard/index.tsx
  src/common/components/PrimaryCard/index.types.ts
  src/common/components/RouteRow/index.styles.ts
  src/common/components/RouteRow/index.tsx
  src/common/components/RouteRow/index.types.ts
  src/common/components/SeatDetailsTable/index.tsx
  src/common/components/SeatDetailsTable/index.types.ts
  src/common/components/TicketDateRow/index.styles.ts
  src/common/components/TicketDateRow/index.tsx
  src/common/components/TicketDateRow/index.types.ts
  src/mock/seats/fixture.ts
  src/mock/ticket/fixture.ts
  src/pages/BookingPaymentPage/index.tsx
  src/routes/booking/payment/index.tsx
  src/stores/useBackwardBusListStore/index.ts
  src/stores/useSearchQueryStore/index.ts
  src/stores/useTicketListStore/index.ts
  src/stores/useTowardBusListStore/index.ts
  src/stories/BookingPaymentPage.stories.tsx
  src/stories/CompanyRow.stories.tsx
  src/stories/FeeSumRow.stories.tsx
  src/stories/PrimaryCard.stories.tsx
  src/stories/RouteRow.stories.tsx
  src/stories/SeatDetailsTable.stories.tsx
  src/stories/TicketDateRow.stories.tsx
  src/theme/index.ts
  src/types/index.ts
Labels: enhancement

#62 feat: reservation store
  src/stores/useReservationStore/index.ts
  src/stores/useReservationStore/index.types.ts
  src/types/index.ts
Labels: enhancement

#64 fix: inconsistent type names
  src/common/components/CompanyRow/index.tsx
  src/common/components/CompanyRow/index.types.ts
  src/common/components/SeatDetailsTable/index.tsx
  src/common/components/SeatDetailsTable/index.types.ts
  src/mock/ticket/fixture.ts
Labels: bug

#77 hofix: set home page as booking page
  src/routes/__root.tsx
  src/routes/index.tsx
Labels: bug

#81 Fix/navigate-to-home-page
  src/common/components/PaymentConfirmation/index.tsx
  src/stories/PaymentConfirmationPage.stories.tsx
Labels: enhancement
