Repository uxplorerss/uxplorers-frontend, pull requests merged in 2024-11, with the labels that each got.

#1 feat: set up vite project
  .gitignore
  .prettierrc
  README.md
  eslint.config.js
  index.html
  package.json
  src/App.tsx
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: enhancement

#5 Feat/2 build global components
  .gitignore
  .storybook/main.ts
  .storybook/preview.tsx
  package.json
  src/App.tsx
  src/common/components/BottomBar/index.styles.ts
  src/common/components/BottomBar/index.tsx
  src/common/components/BottomBar/types.ts
  src/common/components/Card/index.styles.ts
  src/common/components/Card/index.tsx
  src/common/components/Card/types.ts
  src/common/components/Input/index.styles.ts
  src/common/components/Input/index.tsx
  src/common/components/Input/types.ts
  src/common/components/TopBar/index.styles.ts
  src/common/components/TopBar/index.tsx
  src/common/components/TopBar/types.ts
  src/main.tsx
  tsconfig.app.json
  yarn.lock
Labels: enhancement

#10 Deps/add tanstack router
  .gitignore
  .prettierignore
  eslint.config.js
  package.json
  src/main.tsx
  src/routes/__root.tsx
  src/routes/account/index.lazy.tsx
  src/routes/booking/payment/index.tsx
  src/routes/booking/paymentConfirmation/index.tsx
  src/routes/booking/seats/index.tsx
  src/routes/booking/tickets/index.tsx
  src/routes/booking/trips/index.tsx
  src/routes/index.tsx
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: enhancement

#12 hotfix: incorrect route in Link component
  src/routes/__root.tsx
Labels: bug

#11 ci/set up lint, build, and deploy
  .github/workflows/build.yml
  .github/workflows/deploy.yml
  .github/workflows/lint.yml
  eslint.config.js
  package.json
Labels: ci

#15 Ci/sequential build and deploy
  .github/workflows/deploy.yml
Labels: ci

#19 CD/tanstack router settings
  src/main.tsx
  src/routes/__root.tsx
  vite.config.ts
Labels: ci

#20 Revert "index.style.ts file error"
  package-lock.json
  package.json
  src/common/assets/icons/ticketOff.svg
  src/common/assets/icons/ticketOn.svg
  src/routes/booking/tickets/index.styles.ts
  src/routes/booking/tickets/index.tsx
  tsconfig.app.json
  yarn.lock
Labels: bug

#29 Feat/reusable top bar component
  src/assets/CloseIcon.svg
  src/assets/LeftArrowIcon.svg
  src/assets/LogoIcon.svg
  src/common/components/Button/index.tsx
  src/common/components/Button/index.types.ts
  src/common/components/Flex/index.tsx
  src/common/components/FontProvider/index.tsx
  src/common/components/Input/index.tsx
  src/common/components/Input/index.types.ts
  src/common/components/Input/types.ts
  src/common/components/LanguageSwitchButton/index.styles.ts
  src/common/components/LanguageSwitchButton/index.tsx
  src/common/components/LanguageSwitchButton/index.types.ts
  src/common/components/LogoIcon/index.tsx
  src/common/components/TopBar/index.styles.ts
  src/routes/__root.tsx
  src/stories/LanguageSwitchButton.stories.tsx
  src/stories/TopBar.stories.tsx
Labels: enhancement

#25 Feat/22 first start page
  package.json
  src/assets/booking/btn_transfer.svg
  src/common/components/IconButton/index.tsx
  src/common/components/index.ts
  src/routes/__root.tsx
  src/routes/booking/index.tsx
  tsconfig.app.json
  yarn.lock
Labels: enhancement

#30 refactor: add `import type` for readability
  src/common/components/BottomBar/index.tsx
  src/common/components/BottomBar/types.ts
  src/common/components/Button/index.tsx
  src/common/components/Button/index.types.ts
  src/common/components/Card/index.tsx
  src/common/components/Flex/index.styles.ts
  src/common/components/Flex/index.tsx
  src/common/components/Flex/index.types.ts
  src/common/components/IconButton/index.tsx
  src/common/components/Input/index.tsx
  src/common/components/Input/index.types.ts
  src/common/components/LanguageSwitchButton/index.tsx
  src/common/components/TopBar/index.tsx
  src/common/components/TopBar/types.ts
  src/common/components/Typography/index.styles.ts
  src/common/components/Typography/index.tsx
  src/common/components/Typography/index.types.ts
  src/stories/BottomBar.stories.tsx
  src/stories/Button.stories.tsx
  src/stories/Card.stories.tsx
  src/stories/Input.stories.tsx
  src/stories/LanguageSwitchButton.stories.tsx
  src/stories/TopBar.stories.tsx
  src/stories/Typography.stories.tsx
Labels: chore

#31 refactor: enable custom styling via css prop
  src/common/components/BottomBar/index.styles.ts
  src/common/components/BottomBar/index.tsx
  src/common/components/Button/index.tsx
  src/common/components/Button/index.types.ts
  src/common/components/Flex/index.tsx
  src/common/components/Flex/index.types.ts
  src/common/components/Input/index.tsx
  src/common/components/Input/index.types.ts
Labels: refactor

#36 refactor: simplify css prop injection
  .storybook/GlobalStyles/index.tsx
  .storybook/preview.tsx
  src/common/components/ActionBar/index.styles.ts
  src/common/components/ActionBar/index.tsx
  src/common/components/ActionBar/index.types.ts
  src/common/components/Button/index.tsx
  src/common/components/Button/index.types.ts
  src/common/components/Flex/index.tsx
  src/common/components/Flex/index.types.ts
  src/common/components/Input/index.styles.ts
  src/common/components/Input/index.tsx
  src/common/components/Input/index.types.ts
  src/common/components/Typography/index.styles.ts
  src/common/components/Typography/index.tsx
  src/common/components/Typography/index.types.ts
Labels: refactor

#37 Feat/reusable action bar
  src/common/components/ActionBar/index.styles.ts
  src/common/components/ActionBar/index.tsx
  src/common/components/ActionBar/index.types.ts
  src/stories/ActionBar.stories.tsx
  src/stories/MainButton.stories.tsx
Labels: enhancement

#42 ci: copy commit history fully when deploying storybook
  .github/workflows/storybook.yml
Labels: bug, ci

#40 feat/reusable action bar
  src/common/components/ActionBar/index.styles.ts
  src/common/components/ActionBar/index.tsx
  src/common/components/Flex/index.styles.ts
  src/common/components/Flex/index.tsx
  src/common/components/Flex/index.types.ts
  src/common/components/TopBar/index.styles.ts
  src/common/components/TopBar/index.tsx
  src/index.styles.ts
  src/stories/ActionBar.stories.tsx
  src/stories/TopBar.stories.tsx
Labels: enhancement

#44 feat/define-global-states
  package.json
  src/stores/useBackwardBusListStore/index.ts
  src/stores/useBackwardBusListStore/index.types.ts
  src/stores/useSearchQueryStore/index.ts
  src/stores/useSearchQueryStore/index.types.ts
  src/stores/useTicketListStore/index.ts
  src/stores/useTicketListStore/index.types.ts
  src/stores/useTowardBusListStore/index.ts
  src/stores/useTowardBusListStore/index.types.ts
  src/types/index.ts
  yarn.lock
Labels: enhancement

#47 refactor/make destDate prop optional
  src/stores/useSearchQueryStore/index.ts
  src/types/index.ts
Labels: enhancement

#48 refactor/follow-event-handler-conventions
  src/common/components/Seats/Seat/index.tsx
  src/common/components/Seats/Seat/types.ts
  src/common/components/Seats/SelectSeat/index.tsx
  src/common/components/Seats/SelectSeat/types.ts
Labels: enhancement
